#!/bin/bash

# Inspired by "probe" in oe-init-build-env
if [ -n "$BASH_SOURCE" ]; then
    this_script=$BASH_SOURCE
elif [ -n "$ZSH_NAME" ]; then
    this_script=$0
else
    this_script="$(pwd)/setup-environment"
fi

script_dir=$(dirname "$this_script")
script_dir=$(readlink -f "$script_dir")

kalfire_repo_dir=${script_dir}/sources/meta-kalfire-repo
build_dir=${script_dir}/build

target=""

targets=(
    "eone")

for i in ${targets[@]}
do
    if [[ $i == $1 ]]
    then
        target=$1
        break
    fi
done

if [ -z "${target}" ]; then
    echo "Sorry, it does not seem that *$1* is a valid target"
    echo ""

    printf "Supported targets are:\n"
    printf '%s\n' "${targets[@]}"
    return 1
fi

target_templates=${kalfire_repo_dir}/meta-kalfire-${target}/templates
target_scripts=${kalfire_repo_dir}/meta-kalfire-${target}/scripts

. ${script_dir}/sources/poky/oe-init-build-env ${build_dir}

if [ -f ${build_dir}/conf/kalfire_complete ]; then
    return 1
fi

# Common entries for Mender
cat ${kalfire_repo_dir}/templates/local.conf.append >> ${build_dir}/conf/local.conf

# Board specific entries
cp ${target_templates}/bblayers.conf.sample ${build_dir}/conf/bblayers.conf
cat ${target_templates}/local.conf.append >> ${build_dir}/conf/local.conf

if [ -f "${target_scripts}/finish_install.sh" ]; then
    ${target_scripts}/finish_install.sh ${build_dir}
fi

touch ${build_dir}/conf/kalfire_complete
